# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraFrame = QtWidgets.QFrame(self.centralwidget)
        self.cameraFrame.setGeometry(QtCore.QRect(5, 5, 1590, 800))
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.camera = QtWidgets.QLabel(self.cameraFrame)
        self.camera.setGeometry(QtCore.QRect(10, 10, 1570, 975))
        self.camera.setText("")
        self.camera.setAlignment(QtCore.Qt.AlignCenter)
        self.camera.setObjectName("camera")
        self.buttonFrame = QtWidgets.QFrame(self.centralwidget)
        self.buttonFrame.setGeometry(QtCore.QRect(5, 830, 230, 50))
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.saveFrame = QtWidgets.QPushButton(self.buttonFrame)
        self.saveFrame.setGeometry(QtCore.QRect(10, 10, 95, 35))
        self.saveFrame.setObjectName("saveFrame")
        self.record = QtWidgets.QPushButton(self.buttonFrame)
        self.record.setGeometry(QtCore.QRect(120, 10, 95, 35))
        self.record.setObjectName("record")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveFrame.setText(_translate("MainWindow", "Save Frame"))
        self.record.setText(_translate("MainWindow", "Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
